### PR TITLE
Better logic for determining Beat Saber installation directory

### PR DESCRIPTION
**Pull request by VentyCZ**
This PR uses the following steps:
1. Finds out the Steam installation directory from registry (32/64bit)
2. Goes through all the defined library folders
3. Finds the library folder containing Beat Saber and uses it

### CODE REVIEW

**Comment by kinsi55** [comment]
Hey, thank you. I'll try to look into this in a bit

**Comment by VentyCZ** [comment]
@kinsi55 Thank you :) Haven't done any C# in a long while, so even any nitpicks on the code are appreciated!

**Comment by kinsi55** [comment]
Since you asked for it, I nitpicked :P

LGTM tho, I'll include it in the next update whenever that will be, thank you!

**Comment by VentyCZ** [comment]
Np, thanks for the nitpicking too :)

Mostly code style stuff, except for using LINQ - haven't done any C# in looong while, so I totally forgot how to LINQ ;)

**Pull request merged**
